name: PR Test Workflow

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Auto merge the PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --admin --repo ${{ github.repository }} --head ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
